#!/bin/sh
# gen-stagenames — the stage name table and the vanilla file names, as a header.
#
#   sh gen-stagenames.sh <constants.h> <stagetable.c> <files.json> > stagenames.h
#
# WHY GENERATED AND NOT COPIED. modsetcheck has to resolve `stage "STAGE_28"`
# and `stage 0x26` to the same row the loader would, and know whether a row is
# a STAGE_EXTRA row (placeholder content the allocator may hand out) or a level
# the base game ships. The engine keeps that in two places - the STAGE_* values
# in constants.h and g_StageNames[] in stagetable.c, held in step by a
# _Static_assert - and a copy in this tool would drift the day a row is added.
# The same goes for the vanilla file names a stage block may name to mean "use
# the stock file": those come from tools/share/pd-ntsc-final/files.json, which
# is what the loader's own base table is built from.
#
# A name in g_StageNames with no STAGE_* constant is an error here, because it
# would be one in the engine too.
set -eu

constants=$1
stagetable=$2
filesjson=$3

echo "/* generated by gen-stagenames.sh - do not edit, do not commit */"
echo "#ifndef STAGENAMES_H"
echo "#define STAGENAMES_H"
echo

awk '
	/^#define[ \t]+NUM_STAGENUMS[ \t]/ { printf("#define MSC_NUM_STAGENUMS %s\n", $3) }
	/^#define[ \t]+STAGE_TITLE[ \t]/   { printf("#define MSC_STAGE_TITLE %s\n", $3) }
' "$constants"

echo
echo "struct stagename { const char *name; int stagenum; int hasrow; };"
echo

# Names that own a g_Stages row, in table order: every string literal between
# the g_StageNames opener and the closing brace.
awk '
	/g_StageNames\[/ { in_table = 1; next }
	in_table && /^};/ { in_table = 0 }
	in_table {
		line = $0
		while (match(line, /"STAGE_[A-Za-z0-9_]+"/)) {
			print substr(line, RSTART + 1, RLENGTH - 2)
			line = substr(line, RSTART + RLENGTH)
		}
	}
' "$stagetable" > "${TMPDIR:-/tmp}/gen-stagenames.rows.$$"

awk -v rowsfile="${TMPDIR:-/tmp}/gen-stagenames.rows.$$" '
	BEGIN {
		while ((getline r < rowsfile) > 0) { rows[r] = 1; nrows++ }
		close(rowsfile)
		print "static const struct stagename g_StageNameTable[] = {"
	}
	/^#define[ \t]+STAGE_[A-Z0-9_]+[ \t]+0x[0-9a-fA-F]+/ {
		name = $2
		val = $3
		seen[name] = 1
		printf("\t{ \"%s\", %s, %d },\n", name, val, (name in rows) ? 1 : 0)
	}
	END {
		print "};"
		for (r in rows) {
			if (!(r in seen)) {
				printf("gen-stagenames: %s is in g_StageNames but has no STAGE_ constant\n", r) > "/dev/stderr"
				bad = 1
			}
		}
		if (bad) { exit 1 }
	}
' "$constants"

rm -f "${TMPDIR:-/tmp}/gen-stagenames.rows.$$"

echo
echo "#define MSC_NUM_STAGENAMES (sizeof(g_StageNameTable) / sizeof(g_StageNameTable[0]))"
echo

# What each g_Stages row carries for bg, tiles, pads, setup and mpsetup - the
# FILE_* tokens in columns 7..11 of the row. A stage block that omits one of
# those keys inherits the row's, so the checker has to be able to say which.
echo "struct stagerow { const char *name; const char *files[5]; };"
echo
echo "static const struct stagerow g_StageRows[] = {"
awk '
	/g_Stages\[/ { in_table = 1; next }
	in_table && /^};/ { in_table = 0 }
	in_table && /^[ \t]*\/\*0x[0-9a-f]+\*\/[ \t]*STAGE_/ {
		line = $0
		sub(/^[ \t]*\/\*0x[0-9a-f]+\*\/[ \t]*/, "", line)
		gsub(/[ \t]/, "", line)
		n = split(line, f, ",")
		if (n < 11) { next }
		printf("\t{ \"%s\", { \"%s\", \"%s\", \"%s\", \"%s\", \"%s\" } },\n", f[1], f[7], f[8], f[9], f[10], f[11])
	}
' "$stagetable"
echo "};"
echo
echo "#define MSC_NUM_STAGEROWS (sizeof(g_StageRows) / sizeof(g_StageRows[0]))"
echo

# The vanilla file names: every "name": id pair inside the "files" object.
echo "static const char *const g_VanillaFileNames[] = {"
awk '
	{
		line = $0
		if (!in_files) {
			if (!match(line, /"files"[ \t]*:/)) { next }
			in_files = 1
			line = substr(line, RSTART + RLENGTH)
		}
		while (match(line, /"[^"]+"[ \t]*:[ \t]*[0-9]+/)) {
			pair = substr(line, RSTART, RLENGTH)
			sub(/"[ \t]*:.*$/, "", pair)
			sub(/^"/, "", pair)
			printf("\t\"%s\",\n", pair)
			line = substr(line, RSTART + RLENGTH)
		}
	}
' "$filesjson"
echo "};"
echo
echo "#define MSC_NUM_VANILLA_FILES (sizeof(g_VanillaFileNames) / sizeof(g_VanillaFileNames[0]))"
echo
echo "#endif"
