#!/usr/bin/env python3
"""Generate port/src/imgui_ailistnames.h: a name for every ailist id the
debugger can show, keyed by setup.

Sources, in order of preference for a stage list's name:
  1. the setup's own `#define AILIST_FOO 0x0404` (23 of the solo setups)
  2. the function symbol in its `ailists[]` table, `func0404_init_hovercar`
     -> `init_hovercar` (every setup has this; the decomp names them)
Global lists come from g_GlobalAilists[] in src/game/gailists.c, named by
their GAILIST_* constant.

The key is the setup's source basename (`setupame`, `mp_setupame`), which the
overlay derives from the stage's setup file name (`UsetupameZ`) at runtime.
A mod setup the tree does not know about simply shows hex, as before.

Dev-side only: run it when a list is added, commit the header.
    tools/mkailistnames.py [repo root]
"""
import os, re, sys

root = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), '..')
out_path = os.path.join(root, 'port', 'src', 'imgui_ailistnames.h')

entry_re = re.compile(r'\{\s*(func[0-9a-fA-F]{4}_?\w*)\s*,\s*(0x[0-9a-fA-F]+|[A-Z_0-9]+)\s*\}')
define_re = re.compile(r'^#define\s+((?:G)?AILIST_\w+)\s+(0x[0-9a-fA-F]+)', re.M)

def defines_in(text):
    return {m.group(1): int(m.group(2), 16) for m in define_re.finditer(text)}

def table_in(text, table):
    m = re.search(r'struct ailist ' + table + r'\[\]\s*=\s*\{(.*?)\};', text, re.S)
    return m.group(1) if m else ''

rows = []  # (setup, id, name)

# globals
gtext = open(os.path.join(root, 'src', 'game', 'gailists.c')).read()
ctext = open(os.path.join(root, 'src', 'include', 'constants.h')).read()
consts = defines_in(ctext)
for func, ident in entry_re.findall(table_in(gtext, 'g_GlobalAilists')):
    num = int(ident, 16) if ident.startswith('0x') else consts.get(ident)
    if num is None:
        continue
    name = ident[len('GAILIST_'):] if ident.startswith('GAILIST_') else re.sub(r'^func[0-9a-fA-F]{4}_?', '', func)
    rows.append(('', num, name or func))

# setups
setups_dir = os.path.join(root, 'src', 'setups')
for fn in sorted(os.listdir(setups_dir)):
    if not fn.endswith('.c'):
        continue
    setup = fn[:-2]
    text = open(os.path.join(setups_dir, fn)).read()
    local = defines_in(text)
    byid = {v: k[len('AILIST_'):] for k, v in local.items() if k.startswith('AILIST_')}
    for func, ident in entry_re.findall(table_in(text, 'ailists')):
        num = int(ident, 16) if ident.startswith('0x') else local.get(ident, consts.get(ident))
        if num is None:
            continue
        name = byid.get(num) or re.sub(r'^func[0-9a-fA-F]{4}_?', '', func) or func
        rows.append((setup, num, name))

rows.sort(key=lambda r: (r[0], r[1]))

with open(out_path, 'w') as f:
    f.write('// Generated by tools/mkailistnames.py from src/game/gailists.c and\n'
            '// src/setups/*.c (AILIST_* defines, else the ailists[] function names).\n'
            '// Regenerate when a list is added.\n'
            '#ifndef IMGUI_AILISTNAMES_H\n#define IMGUI_AILISTNAMES_H\n\n'
            '#include <string.h>\n\n'
            'struct imguiAilistNameEntry { const char *setup; unsigned short id; const char *name; };\n\n'
            'static const struct imguiAilistNameEntry g_ImGuiAilistNames[] = {\n')
    for setup, num, name in rows:
        f.write('\t{ "%s", 0x%04x, "%s" },\n' % (setup, num, name))
    f.write('};\n\n'
            '// setup is the setup source basename ("setupame"), or NULL/"" for a\n'
            '// global list. Linear: only ever walked while a combo is open or for\n'
            '// one preview per open chr node.\n'
            'static const char *imguiAilistName(const char *setup, unsigned int id)\n{\n'
            '\tconst char *key = setup ? setup : "";\n'
            '\tfor (unsigned int i = 0; i < sizeof(g_ImGuiAilistNames) / sizeof(g_ImGuiAilistNames[0]); i++) {\n'
            '\t\tif (g_ImGuiAilistNames[i].id == id && strcmp(g_ImGuiAilistNames[i].setup, key) == 0) {\n'
            '\t\t\treturn g_ImGuiAilistNames[i].name;\n'
            '\t\t}\n'
            '\t}\n'
            '\treturn NULL;\n}\n\n#endif\n')

print('%d names -> %s' % (len(rows), out_path))
